// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDry5AZBl906DvvHl5tcN-wrNCI3pab_cc',
    appId: '1:942498391289:android:abf9c97b206527c1d9ae28',
    messagingSenderId: '942498391289',
    projectId: 'notlarim-b14a5',
    databaseURL: 'https://notlarim-b14a5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'notlarim-b14a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIG7JRSpqDc5mXxzvQ0Vr958m0Kl-0efA',
    appId: '1:942498391289:ios:6613fdf35a9e1151d9ae28',
    messagingSenderId: '942498391289',
    projectId: 'notlarim-b14a5',
    databaseURL: 'https://notlarim-b14a5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'notlarim-b14a5.appspot.com',
    iosBundleId: 'com.example.notlarim',
  );
}
